version: '3.8'

services:
  nginx:
    image: nginx
    build:
      context: docker/nginx
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/www.conf:/etc/nginx/conf.d/www.conf
    ports:
      - "8080:80"
    container_name: d_nginx
    depends_on:
      - php-fpm
      - postgres
    restart: always
    networks:
      - myProject


  php-fpm:
    image: php-fpm
    build:
      context: docker/php-fpm
    restart: always
    container_name: d_php
    depends_on:
      - postgres
    networks:
      - myProject
    volumes:
      - ./app:/var/www/project


  postgres:
    image: postgres:latest
    restart: always
    container_name: d_postgres
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      POSTGRES_ROOT_PASSWORD: "root"
      POSTGRES_DB: "symfony"
      POSTGRES_USER: "symfony"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    networks:
      - myProject

networks:
  myProject:
    driver: bridge
